### ISSUE TITLE
no data from temperature sensors

### ISSUE THREAD

**Issue by bereska** [aquaticus/nexus433#11]
thanks for the great program, well done!
after setting it all up I don't seem to be getting any data from two temperature sensors (Oregon Scientific RMR382 and Ea2 AL802):

pi@bereskapi-ha:~/nexus433 $ sudo nexus433 --verbose -n 17
Loading configuration from /etc/nexus433.ini
Reading data from 433MHz receiver on /dev/gpiochip0 pin 17.
Decoder resolution: 1 µs; tolerance: 300 µs
Connected to MQTT broker.

how can i debug this?
are my sensors not nexus compatible?

thank you

**Comment by bereska** [comment]
found this:
http://wmrx00.sourceforge.net/Arduino/OregonScientific-RF-Protocols.pdf
it mentions Manchester coding
no dice?

**Comment by aquaticus** [comment]
If you have logic analyzer e.g. Saleae you can just connect to 433MHz receiver data pin and see what's going on.
If not, you can add `printf("1");` in line 108 and `printf("0");` in line of `decoder.cpp` (and `printf("\n");` in line 68 ) to see if any bits are decoded.
Make sure you got power and data line properly connected and the sensor is close to the receiver (to make sure signal is good enough).
If you properly connected everything most likely the sensor is not compatible with nexus protocol (I have no idea what protocol they're using).

**Comment by aquaticus** [comment]
Just saw you comment about manchaster coding. That definitely means sensor is not compatible.
