### ISSUE TITLE
Howto use this nexus433 mqtt in Domoticz

### ISSUE THREAD

**Issue by ldijkman** [aquaticus/nexus433#14]
Hello

could someone explain how to use this with domoticz
i have 4 Digoo DG-R8B 433Mhz temp humid sensors
fridge freezer living outdoor
what i do now is in main.cpp i write the sensors to a html file web server location on disk
http://84.106.2.21:8888/wirelestemps.html
and domoticz on another pi is reading the above 4 sensor html page every minute with a lua script
catching what ever from the 4 sensors is on at that moment
http://test:test@84.106.2.21:8080/#/Floorplans
it works
but its not how it should be

can anyone explain how to do the mqtt with domoticz?
http://84.106.2.21:8888/forum/index.php?action=view&id=213

i can recieve some sensor values on my phone using mqtt client localip:1883 
and nexus433/#

but im stuck 

Thanks
greetings luberth from the netherlands

Something else
if i want the only the outdoor sensor temperature humidity for display on a html webserver page
so that other people in my neighborhood can see the outdoor temperature in Bangert Andijk NL
how would you do that
my coding skills are not that good  ;-)
next if is not working ;-(
if ((it->GetId()) = "bc")VERBOSE_PRINTF("this bc is the id of outoor sensor" ){
                        do verbose print of outdoor sensor to html file in webserver directory
}

**Comment by aquaticus** [comment]
Better ask on Domoticz forum how to connect MQTT sensor.
