### ISSUE TITLE
Two Nexus433 instances on two Raspberry's

### ISSUE THREAD

**Issue by wachux** [aquaticus/nexus433#17]
HI,

Had one Raspberry Pi with the Mosquitto Broker and Nexus433. I had problem with receiving signals from the sensors in the far end of home so I decided to buy another Raspberry, install second instance of Nexus433 on it and connect it to the Mqtt borker on first Raspberry. When Itry to run the second instance of Nexuss433 i get 
"Connected to MQTT broker.
MQTT Disconnected. Connection Refused: unknown reason.
MQTT Reconnecting" 
and this message appears in a loop until i kill the process. I read that this is caused by the same ID of MQTT client trying to connect to broker. Is there a way to change the ID of the second Nexus433 instance ?

**Comment by wachux** [comment]
I managed to do this using 
"use_username_as_clientid" in the Mosquitto configuration file.

**Comment by aquaticus** [comment]
Mosquitto does not accept two clients with the same ID. The option you used, force different IDs.
