### ISSUE TITLE
Nexus433 keeps RPi0 W CPU at 99% load

### ISSUE THREAD

**Issue by berechetflorin** [aquaticus/nexus433#19]
I installed your solution (congrats for it, it's the only working one for DG-R8H) on a Raspberry Pi0. With htop I can see nexus433 thread taking 99% of CPU. Is this normal? I have a fresh image on Raspbian, the only role for RPi is to be a gateway between 433Mhz and Mosquitto under Hassio.
Thanks!

**Comment by aquaticus** [comment]
It shouldn't be 99% but the load is high anyway. The problem with this software is that it must probe 433MHz signal quite often which takes processor time. You can decrease resolution which should help but also increases fail rate.

**Comment by berechetflorin** [comment]
I decreased resolution to 4 and now the CPU load is at about 70%. I will experiment different values until I will find the balance between the fail rate and processor load. I still don't know if it is normal that `htop` shows 2 nexus threads. This happens in both cases if I start the service with `sudo service nexus433 start` or I just start the process with `sudo nexus433 --verbose`. Again, is this normal?
![Capture](https://user-images.githubusercontent.com/61693146/75768985-1044d480-5d4e-11ea-9931-5d4afcecf180.GIF).
 I keep asking this because I had a very hard time installing the libgpiod library on RPi0 and I don't know if I did everything right eventually (For the sake of keeping things organized here on Github I'll open a separate topic about the installation)
Thanks!

**Comment by aquaticus** [comment]
This is strange. It should be only one process. I don't think it's a problem of gpio lib as it does not start an extra process. Based on PIDs these  2 processes were started one by one. 
What happens when you stop the service/program. Both processes disappear from the list?

**Comment by aquaticus** [comment]
Found where's the problem. This is feature of `htop`, it shows additionality kernel threads.

**Comment by berechetflorin** [comment]
Ok,  so this is something normal, it won't affect nexus433,  it's just the way `htop` displays processes. Thank you for clarification!
