### ISSUE TITLE
nexus433 service won't connect to MQTT broker at start-up

### ISSUE THREAD

**Issue by berechetflorin** [aquaticus/nexus433#20]
I enabled nexus433 to run as a service at start-up with:
`sudo systemctl enable nexus433`
And it starts after reboot... kind of, I don't find it with htop and  `sudo service nexus433` status displays: 
```
root@raspberrypi:/home/pi# service nexus433 status
● nexus433.service - 433MHz sensor receiver
   Loaded: loaded (/etc/systemd/system/nexus433.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-03-03 11:05:06 GMT; 1min 32s ago
 Main PID: 234 (code=exited, status=249)

Mar 03 11:05:05 raspberrypi systemd[1]: Started 433MHz sensor receiver.
Mar 03 11:05:06 raspberrypi nexus433[234]: Loading configuration from /etc/nexus433.ini
Mar 03 11:05:06 raspberrypi nexus433[234]: Unable to connect to MQTT server.
Mar 03 11:05:06 raspberrypi nexus433[234]: Connection Refused: unknown reason.
Mar 03 11:05:06 raspberrypi systemd[1]: nexus433.service: Main process exited, code=exited, status
Mar 03 11:05:06 raspberrypi systemd[1]: nexus433.service: Unit entered failed state.
Mar 03 11:05:06 raspberrypi systemd[1]: nexus433.service: Failed with result 'exit-code'.
```
But if I manually start the service with `sudo service nexus433 start` it will start and run without any problem. As the log says, the MQTT broker refuses the connection but if I do it manually, it works. 
My MQTT broker is Mosquitto which is installed under Hassio, onto another machine. I checked Mosquitto's logs, no entry found related to these lines:
```
Mar 03 11:05:06 raspberrypi nexus433[234]: Unable to connect to MQTT server.
Mar 03 11:05:06 raspberrypi nexus433[234]: Connection Refused: unknown reason.
```
The MQTT credentials are fine, I double checked them in `/etc/nexus433.ini` (I guess this is the configuration file it is used for start-up, right? I also verified the path:` /etc/systemd/system/`, the file `nexus433.service` is in the right place.
I understood from the documentation that after every change something in the .ini files in the release, I must use `make` and `make install` command, which I did everytime.
Any other ideea to solve the start-up issue with nexus433?
Thanks!

**Comment by aquaticus** [comment]
After changing configuration file you must restart service (or stop/start program when running from command line).
`make install` overrides configuration file with default one. That's the reason you cannot connect to MQTT as there are no credentials in file. Use `make install` only once to install files.

**Comment by berechetflorin** [comment]
As a matter of fact I modified the file  /home/pi/nexus433/nexus433.ini.in with my credentials. So everytime I use `make` or `make install` the file `/etc/nexus433.ini` is written with the right credentials. I wonder if the file` /etc/systemd/system/nexus433.service` is ok like this:
```
[Unit]
Description=433MHz sensor receiver
After=network-online.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/nexus433

[Install]
WantedBy=multi-user.target
```

**Comment by aquaticus** [comment]
This happens when you start service manually or only when the board boots up? If this is the second case, most likely MQTT server still does not start when nexus service is running. You must add dependence on MQTT to `nexus433.service` (or just a delay).

**Comment by aquaticus** [comment]
Just realised you're running the software on RPI0, so most likely you have no MQTT server on the same machine. My above statement makes no sense.

**Comment by berechetflorin** [comment]
Yes,  it is the second case,  when the  RPi0 board boots.  The MQTT server is on another machine (Home Assistant on another Raspberry Pi). Something happens during the boot sequence,  I have to find a way to check if the nexus433 configuration file is loaded at the right time before  connecting to the MQTT server.

**Comment by berechetflorin** [comment]
Good news, I solved the problem. As I imagine, the service `nexus433` couldn't connect to the remote MQTT server at boot sequence because it was starting faster than the networking was ready (although there is line in `nexus433.service` with `After=network-online.target`, this doesn't guarantee that a connection with Mosquitto broker is already possible). I added the line:
`ExecStartPre=/bin/sh -c 'until ping -c1 192.168.1.8; do sleep 1; done;'` (it waits until it gets a valid ping) before the line: `ExecStart=/usr/local/bin/nexus433` in file `/etc/systemd/system/nexus433.service`

**Comment by slavkoja** [comment]
Beware, the `network-online.target` (at least on debian) is not real waiting by default. It must be activated by using systemd's networking or by setting proper `WAIT_ONLINE_METHOD` in `/etc/default/networking`.

The default one (`ifup`) doesn't wait to be really on-line (eg. DHCP can be still in progress). Try to use one of `route` or `ping`/`ping6` method with appropriate related settings...

**Comment by berechetflorin** [comment]
Yes, I suspected this line didn't helped too much for starting `nexus433.service` with the proper timing. That's why I tested with the  `until ping`. Anyway, the gateway is now working perfectly for me, all my "untamed" R8H sensor are now fully integrated with Home Assistant. Thank you @aquaticus for this!

**Comment by aquaticus** [comment]
Probably it would be the best to refactor initial MQTT connection routine to try all the time.
