### ISSUE TITLE
Request for line input failed. And MQTT not connecting.

### ISSUE THREAD

**Issue by igarreta** [aquaticus/nexus433#22]
I have a Raspberry Pi 3, and installed nexus433 with a RXB6 receptor. It worked perfectly on the first attempt and was able to recive the data from 3 Digoo DG-R8H sensors.
   After a few days I had some hardware issues (apparently due to a faulty power supply), and afterwards nexus433 stopped working. It exited with the following messages:

```
Loading configuration from /etc/nexus433.ini
Request for line input failed.
```

   I upgraded raspbian with:

```
sudo apt update
sudo apt full-upgrade
```

   And the `Request for line input failed.` error dissapeared, but nexus433 was not longer able to connect to MQTT:

```
pi@raspberrypi1:~ $ sudo nexus433 --verbose -n 22
Loading configuration from /etc/nexus433.ini
Reading data from 433MHz receiver on /dev/gpiochip0 pin 22.
Decoder resolution: 1 µs; tolerance: 300 µs
Connected to MQTT broker.
MQTT Disconnected. Connection Refused: unknown reason.
```
   My MQTT sever is in the same Pi, and working properly

`pi@raspberrypi1:~ $ mosquitto_sub -h 127.0.0.1 -p 1883 -t +/# -v`

   Is able to connect and display MQTT messages from other publishers, and I made no changes to `/etc/nexus433.ini`

   I reinstalled nexus433 and rebooted the Pi, with the same effect.

   Can you help me troubleshoot this problem?

**Comment by aquaticus** [comment]
Hi,

did you solve this problem?

**Comment by igarreta** [comment]
> Hi,
> 
> did you solve this problem?

Quite.
 
I did not "solved" the problem, since I have done nothing new since I wrote the issue, but I have just checked and nexus433 was running without errors. It wasn't reading data because it was configured to the wrong pin. I changed this and is now running fine.

Thanks for asking (and for your development)
