### ISSUE TITLE
“Request for line input failed” when runnings as addon

### ISSUE THREAD

**Issue by CarstenHess** [aquaticus/nexus433#26]
Hi,

I’m working on a set of addon-scripts to install your nexus433 service as an addon on hass.io, and have it building, and can run the executable in verbose mode (starting it as a service comes later when it works).

But every time It tries to run the executable it responds “Request for line input failed.” - the addon has acces to /dev/gpiochip0 (evidenced by the fact that it doesnt output ano ofthe other gpio errors).

I was hoping that perhaps you could help me by explaining at bit about what this specific error means and what typically could cause this? 

Thanks in advance

**Comment by aquaticus** [comment]
Hi
try to run executable as root. If it helps, that means you have to set proper permssions for /dev/gpioXXXX.

**Comment by aquaticus** [comment]
The other reason  is that other program already is using pin you confgured for receiver. Try to setup any other pin and see if you still got the same error.

**Comment by CarstenHess** [comment]
Thanks for your reply,
I am already sudo'ing the executable, so I will have to try to switch pins - I'll let you now how it goes 😄

**Comment by aquaticus** [comment]
You can use `gpioinfo` tool (it's part of libgpiod if you compiled with tools enabled)  to list pins and which program uses tham to diagnose the problem.

**Comment by CarstenHess** [comment]
The tip about the `gpioinfo` tool really helped, thanks! -- I've switched pin, and now it starts with no issues -- unfortunately it looks like my temperature sensor does not support the nexus protocol since I get no data at all, but that has nothing to do with your code 😸
