### ISSUE TITLE
Add support for external LED

### ISSUE THREAD

**Issue by aquaticus** [aquaticus/nexus433#3]
Add support for LED connected to one of the I/O pins.

**Comment by pvarman** [comment]
Hi - would be a great idea - I have a Pi Explorer Hat which has 4 leds controlled by activating a selected GPIO pin. Being able to use these to show receiving on data would help with debugging receiver devices.

**Comment by aquaticus** [comment]
I implement this when I finally find 220Ohm resistor to setup test circuit :-)
