### ISSUE TITLE
Adding encoding info of the nexus protocol

### ISSUE THREAD

**Issue by vjaunet** [aquaticus/nexus433#45]
Hi,
thanks for this excellent tool. While trying to build a small rf transmitter based on a µC using the nexus protocol, I struggled to find information on how the temperature is encoded. Seems to be encoded as 12bits signed integer containing the temperature value in celsius degrees multiplied by 10.
Could this information be added to the Help files ?
Thanks a lot,
Vincent

**Comment by aquaticus** [comment]
Yeah, why not.
