### ISSUE TITLE
where did you get your module from?

### ISSUE THREAD

**Issue by evanrich** [aquaticus/nexus433#7]
found some on amazon and aliexpress, but they don't specifically state if they support the nexus protocol or not... here's one for example:

https://www.amazon.com/433MHz-Wireless-Transmitter-Receiver-Module/dp/B07FHYPVJ6/ref=sr_1_2?ie=UTF8&qid=1536630561&sr=8-2&keywords=433mhz+antenna+receiver&dpID=41--V%252BK0mJL&preST=_SX300_QL70_&dpSrc=srch

Can you post where you got yours?

**Comment by aquaticus** [comment]
You never find nexus protocol explicitly stated. The important thing is that module must support ASK modulation. 
The module from Amazon should be ok. Note that it got an extra CS pin. You must connect it to logic 1 or 0 (consult doc which state selects the chip).
Here is Aliexpress link to module type I'm using https://m.aliexpress.com/item/32840911993.html

**Comment by evanrich** [comment]
Thanks!
