### ISSUE TITLE
Add repeater mode

### ISSUE THREAD

**Issue by aquaticus** [aquaticus/nexus433#8]
Add support for 433 MHz transmitter.
Nexus encoder implementation needed.
This should work in 2 modes:
1. Transmit 433 MHz data in Nexus protocol based on data from MQTT topic.
2. Automatically transmit data received from 433 MHz received.

**This functionality requires external hardware (433 MHz transmitter)**

**Comment by thehaxxa** [comment]
I would find the functionality very useful too, (for interfacing Home Assistant with RF devices.)
