### ISSUE TITLE
Refactor initial MQTT connection procedure

### ISSUE THREAD

**Issue by aquaticus** [aquaticus/nexus433#9]
When the program starts it currently tries **once** get connected to MQTT broker. If there is connection error (e.g. no broker running) it stops.

If connection is lost when program passes initialization, it keep connecting all the time.

It should repeat connecting infinitely at the initialization stage.

**Comment by pvarman** [comment]
Hi - what about if the MQTT connection is refused. Currently it continues to try to connect. Would be useful to output more some error info to help diagnose issue..
For example, I have an issue connecting to the embedded MQTT broker in Homeassistant - the error on HA says ' [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"  '. 
Would be useful to be able to see (and control) what MQTT protocol version is being used to connect.

**Comment by aquaticus** [comment]
yeah, more diagnostic info would be probably quite useful as MQTT connection is essential.
Have you solved problem with HA MQTT server? If so, how?

**Comment by pvarman** [comment]
No - both apps on same Pi, so wanted to see what is actually sent by the Nexus client to help solve.

**Comment by aquaticus** [comment]
It seems nexus mosquitto library is using version of MQTT protocol Home Assistant does not understand.
Probably using `libmosquittopp-dev` in older version could resolve that problem.
